OIPR:
  # use this config for the special scenario dataset
  l_dis: 5
  l_obs: 20
  b_dur: 0.5
  # use this config for general cases
  # l_dis: 'auto'
  # l_obs: 'auto'
  # b_dur: 0.5
rl: 3  # round length